spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hntdb
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: hntapp-secret-key-2026-must-be-at-least-32-characters-long
  expiration: 86400000

server:
  port: 8080